import languageModel from "./../../utils/languageModel";

function ServeLangItem() {
  const langCntnt = languageModel();
  // Ensure we always return an object with default values for SSR compatibility
  return langCntnt && typeof langCntnt === "object"
      ? langCntnt
      : {
          About: "Hakkında",
          About_us: "Hakkımızda",
          Accept_All: "Tümünü Kabul Et",
          Account: "Hesap",
          Action: "İşlem",
          Active: "Aktif",
          Add: "Ekle",
          Add_New: "Yeni Ekle",
          Add_New_Address: "Yeni Adres Ekle",
          Add_To_Cart: "Sepete Ekle",
          Add_To_Compare: "Karşılaştır",
          Add_To_Wishlist: "Favorilere ekle",
          Add_new_address: "Yeni adres ekle",
          Address: "Adres",
          Addresses: "Adresler",
          All_Categories: "Tüm Kategoriler",
          All_Popular_Product: "Tüm Popüler Ürünler",
          All_Seller: "Tüm Satıcılar",
          Already_have_an_Account: "Zaten Hesabınız Var mı",
          Already_in_Cart: "Sepette Zaten Var",
          Amount: "Tutar",
          Apply: "Uygula",
          Apply_Coupon: "Kupon Uygula",
          Are_You_Sure: "Emin misiniz?",
          Are_you_sure__you_want_to_Logout: "Çıkış yapmak istediğinize emin misiniz",
          Availability: "Stok Durumu",
          Back_to_Shop: "Mağazaya Dön",
          Bank_Payment: "Banka Ödemesi",
          Become_seller: "Satıcı Ol",
          Best_Selling: "En Çok Satanlar",
          Bill_Details: "Fatura Detayları",
          Billing_Address: "Fatura Adresi",
          Blog_Not_Found: "Blog Bulunamadı",
          Brands: "Markalar",
          Cancel: "İptal",
          Cart: "Sepet",
          Cash_On_Delivery: "Kapıda Ödeme",
          Categories: "Kategoriler",
          Change_Password: "Şifre Değiştir",
          Checkout: "Ödeme",
          Checkout_Now: "Şimdi Ödeme Yap",
          Choose_Product: "Ürün Seç",
          City: "Şehir",
          Clean_Wishlist: "İstek Listesini Temizle",
          Clear_Cart: "Sepeti Temizle",
          Clear_wishlist: "İstek listesini temizle",
          Comments: "Yorumlar",
          Completed: "Tamamlandı",
          Confirm_Email: "E-postayı Onayla",
          Confirm_Password: "Şifreyi Onayla",
          Confirmation: "Onay",
          Contact: "İletişim",
          Contact_Info: "İletişim Bilgileri",
          Contact_Us: "İletişim",
          Continue_as_Guest: "Misafir Olarak Devam Et",
          Country: "Ülke",
          Coupon_Applied: "Kupon Uygulandı",
          Create_Account: "Hesap Oluştur",
          Create_Seller_Account: "Satıcı Hesabı Oluştur",
          Customers_Feedback: "Müşteri Geri Bildirimleri",
          Dashboard: "Kontrol Paneli",
          Date: "Tarih",
          Days: "Gün",
          Declined: "Reddedildi",
          Delete: "Sil",
          Delete_Account: "Hesabı Sil",
          Delivered: "Teslim Edildi",
          Delivered_On: "Teslim Edildi",
          Delivered_on: "Teslim edildi",
          Delivery_Completed: "Teslimat Tamamlandı",
          Delivery_Date: "Teslimat Tarihi",
          Description: "Açıklama",
          Discount_Products: "İndirimli Ürünler",
          Discount_code: "İndirim kodu",
          Discount_coupon: "İndirim kuponu",
          Dontt_have_an_account: "Hesabınız yok mu",
          Edit_Profile: "Profili Düzenle",
          Email: "E-posta",
          Email_Address: "E-posta Adresi",
          Email_or_Phone: "E-posta veya Telefon",
          Empty_You_dont_Cart_any_Products: "Boş! Sepetinizde ürün yok",
          Empty_You_dont_Wishlist_any_Products: "Boş! İstek listenizde ürün yok",
          Enter_Code: "Kodu Girin",
          Enter_Report_Note: "Rapor Notu Girin",
          Enter_Report_Ttile: "Rapor Başlığı Girin",
          Enter_valid_email: "Geçerli e-posta girin",
          Enter_your_order_tracking_number_and_your_secret_id: "Sipariş takip numaranızı ve gizli kimliğinizi girin",
          FAQ: "SSS",
          Fast_Delivery: "Hızlı Teslimat",
          Features: "Özellikler",
          Fill_the_form_below_or_write_us_We_will_help_you_as_soon_as_possible: "Aşağıdaki formu doldurun veya bize yazın, size en kısa sürede yardımcı olacağız",
          Find_Product: "Ürün Bul",
          First_Name: "Ad",
          Follow_our_newsletter_to_stay_updated_about_us: "Bizi takip etmek için bültenimize abone olun",
          Forgot_password: "Şifremi Unuttum",
          Free_Delivery: "Ücretsiz Teslimat",
          Frequently_asked_questions: "Sık sorulan sorular",
          Get_In_Touch: "İletişime Geç",
          Get_Our: "Uygulamamızı",
          Get_Return_within: "",
          Get_the_Coupon: "Kuponu Al",
          Go_To_Cart: "Sepete Git",
          Have_Any_Qustion: "Sorunuz mu Var",
          Hello: "Merhaba",
          Hi: "Merhaba",
          Highest_Price: "En Yüksek Fiyat",
          Hours: "Saat",
          I_Consent_to_the_Privacy_Policy: "Gizlilik Politikasını Kabul Ediyorum",
          In_Stock: "Stokta Var",
          Introduction: "Tanıtım",
          Invalid_Credentials: "Geçersiz Bilgiler",
          Item_Added_Successfully: "Ürün Başarıyla Eklendi",
          Item_added: "Ürün eklendi",
          Item_in_your_cart: "Sepetinizdeki Ürün",
          Items_in_Your_Cart: "Sepetinizdeki Ürünler",
          Its_Make_easy_for_you_life: "Hayatınızı kolaylaştırır!",
          Last_Name: "Soyad",
          Latest_Post: "Son Yazı",
          Loading: "Yükleniyor...",
          Log_In: "Giriş Yap",
          Login: "Giriş Yap",
          Login_Successfully: "Başarıyla Giriş Yapıldı",
          Logout: "Çıkış Yap",
          Low_Price: "Düşük Fiyat",
          MOBILE_APP_VERSION: "MOBİL UYGULAMA SÜRÜMÜ",
          Main_Menu: "Ana Menü",
          Make_Your_Payment: "Ödemenizi Yapın",
          Max_5mb: "Maksimum 5mb",
          Message: "Mesaj",
          Messages: "Mesajlar",
          Minutes: "Dakika",
          Mobile_App: "İndirin",
          My_Latest_News: "Son Haberlerim",
          My_Offers: "Tekliflerim",
          Name: "İsim",
          New_Arrival: "Yeni Gelenler",
          New_Orders: "Yeni Siparişler",
          New_Password: "Yeni Şifre",
          No_Address: "Adres Yok",
          No_Category: "Kategori Yok",
          No_items_found: "Ürün bulunamadı",
          Not_Now: "Şimdi Değil",
          OFF: "İNDİRİM",
          OTP: "OTP",
          Offers: "Teklifler",
          Office: "Ofis",
          Old_Password: "Eski Şifre",
          Order: "Sipariş",
          Order_Amount: "Sipariş Tutarı",
          Order_ID: "Sipariş No",
          Order_No: "Sipariş No",
          Order_Summary: "Sipariş Özeti",
          Other: "Diğer",
          Our_Newsletter: "Bültenimiz",
          Our_blogs: "Bloglarımız",
          Out_of_Stock: "Stokta Yok",
          Pages: "Sayfalar",
          Password: "Şifre",
          Payment_Declined: "Ödeme Reddedildi",
          Pending: "Beklemede",
          Pending_review: "Bekleyen inceleme",
          Personal_Info: "Kişisel Bilgiler",
          Personal_Information: "Kişisel Bilgiler",
          Phone_Number: "Telefon Numarası",
          Place_Order: "Sipariş Ver",
          Place_Order_Now: "Şimdi Sipariş Ver",
          Please_Login_First: "Lütfen Önce Giriş Yapın",
          Please_Select_Shipping_Rule: "Lütfen Kargo Kuralını Seçin",
          Please_Select_Your_Payment_Method: "Lütfen Ödeme Yönteminizi Seçin",
          Please_verify_your_account__If_you_didnt_get_OTP__please_resend_your_OTP_and_verify: "Lütfen hesabınızı doğrulayın. OTP almadıysanız, lütfen OTP'nizi yeniden gönderin ve doğrulayın",
          Price: "Fiyat",
          Price_Range: "Fiyat Aralığı",
          Print_PDF: "PDF Yazdır",
          Privacy_Policy: "Gizlilik Politikası",
          Proceed_to_Checkout: "Ödemeye Geç",
          Product: "Ürün",
          Product_Compaire: "Ürün Karşılaştır",
          Product_Comparison: "Ürün Karşılaştırma",
          Product_Details: "Ürün Detayları",
          Product_categories: "Ürün Kategorileri",
          Product_from_Shop: "Mağazadan Ürün",
          Progress: "İşlemde",
          Re_enter_Password: "Şifreyi Tekrar Girin",
          Quick_View: "Hızlı bakış",
          Read_Only: "Sadece Oku",
          Read_more: "Devamını oku",
          Related_Product: "İlgili Ürünler",
          Remember_Me: "Beni Hatırla",
          Remove_From_Wishlist: "Favorilerden çıkar",
          Remove_Successfully: "Başarıyla Kaldırıldı",
          Remove_from_Cart: "Sepetten Çıkar",
          Report_Products: "Ürünü Bildir",
          Report_This_Item: "Bu Ürünü Bildir",
          Reports_Headline_here: "Rapor Başlığı Buraya",
          Resend: "Yeniden Gönder",
          Reset: "Sıfırla",
          Reset_Password: "Şifreyi Sıfırla",
          Reviews: "Yorumlar",
          SKU: "SKU",
          SUBTOTAL: "ALT TOPLAM",
          Save_Address: "Adresi Kaydet",
          Search: "Ara",
          Search_products: "Ürün Ara",
          Seconds: "Saniye",
          See_all_Reviews: "Tüm Yorumları Gör",
          Select: "Seç",
          Select_One: "Birini Seç",
          Select_your_payment_system: "Ödeme sisteminizi seçin",
          Seller_Info: "Satıcı Bilgileri",
          Seller_Information: "Satıcı Bilgileri",
          Seller_Login: "Satıcı Girişi",
          Seller_terms_and_conditions: "Satıcı şartları ve koşulları",
          Sellers: "Satıcılar",
          Send: "Gönder",
          Send_Now: "Şimdi Gönder",
          Send_OTP: "OTP Gönder",
          Send_Product: "Ürün Gönder",
          Send_Us_A_Message: "Bize Mesaj Gönderin",
          Settings: "Ayarlar",
          Share_This: "Paylaş",
          Shipping: "Kargo",
          Shipping_Address: "Teslimat Adresi",
          Shipping_Cost: "Kargo Ücreti",
          Shop: "Mağaza",
          Shop_Information: "Mağaza Bilgileri",
          Shop_Name: "Mağaza Adı",
          Shop_Now: "Şimdi Alışveriş Yap",
          Show_more: "Daha fazla göster",
          Showing: "Gösteriliyor",
          Sign_Out: "Çıkış Yap",
          Signup: "Kayıt Ol",
          Something_went_wrong: "Bir şeyler yanlış gitti!",
          Somethings_went_wrong: "Bir şeyler yanlış gitti",
          Sorry_We_cantt_Find_that_page: "Üzgünüz! Bu sayfayı bulamıyoruz!",
          Specification: "Özellikler",
          Star_Rating: "Yıldız Puanı",
          State: "İl",
          Subject: "Konu",
          Submit_Report: "Raporu Gönder",
          Submit_Review: "Yorum Gönder",
          Subscribe: "Abone Ol",
          Support: "Destek",
          Switch_Dashboard: "Satıcı Paneline Geçiş Yap",
          Tags: "Etiketler",
          Term_and_Conditions: "Şartlar ve Koşullar",
          Total: "Toplam",
          Total_Amount: "Toplam Tutar",
          Total_Orders: "Toplam Sipariş",
          Total_Paid: "Toplam Ödenen",
          Total_Price: "Toplam Fiyat",
          Track_Now: "Şimdi Takip Et",
          Track_Order: "Sipariş Takibi",
          Track_Your_Order: "Siparişinizi Takip Edin",
          Tracking_number: "Takip numarası",
          Type: "Tip",
          Type_Here: "Buraya Yazın",
          Update_Cart: "Sepeti Güncelle",
          Update_Cover: "Kapak Resmini Güncelle",
          Update_Logo: "Logoyu Güncelle",
          Update_Password: "Şifreyi Güncelle",
          Update_Profile: "Profili Güncelle",
          Update_address: "Adresi güncelle",
          Verify: "Doğrula",
          Verify_You: "Doğrula",
          View_Cards: "Kartları Görüntüle",
          View_Cart: "Sepeti Görüntüle",
          View_Details: "Detayları Görüntüle",
          View_More: "Daha Fazla Gör",
          View_Shop: "Mağazayı Görüntüle",
          View_by: "Görünüm",
          Welcome_to_your_Profile: "Profilinize Hoş Geldiniz",
          Wishlist: "İstek Listesi",
          Write_Your_Reviews: "Yorumunuzu Yazın",
          Your_Compare_List_Is_Empty: "Karşılaştırma Listeniz Boş",
          Your_Dashboard: "Kontrol Paneliniz",
          Your_address_Here: "Adresiniz Buraya",
          Your_order_is_declined: "Siparişiniz reddedildi",
          app_info: "Uygulama Bilgisi",
          blogs: "Bloglar",
          blogs_details: "Blog Detayları",
          cancel: "iptal",
          cart: "Sepet",
          category: "kategori",
          checkout: "ödeme",
          compare: "karşılaştır",
          dashboard: "Kontrol Paneli",
          delete: "sil",
          field_required: "alan gerekli",
          filter: "filtre",
          free_shipping: "Ücretsiz Kargo",
          home: "Ana Sayfa",
          home_delivery: "Ev Teslimatı",
          leave_a_comment: "yorum bırak",
          next: "Sonraki",
          of: "/",
          order_number: "sipariş numarası",
          order_tracking_nubmer: "sipariş takip numarası",
          phone: "Telefon",
          products: "Ürünler",
          profile: "Profil",
          promo_code: "promosyon kodu",
          quantity: "Miktar",
          results: "sonuç",
          review: "inceleme",
          see_all: "Tümünü gör",
          sign_up_free: "ücretsiz kayıt ol",
          total: "Toplam",
          wishlist: "istek listesi",
        };
}

export default ServeLangItem;
