<?php

/**
 * Kuaför, güzellik salonu ve berber blog içerikleri — kısa, SEO odaklı.
 */
return [
    'categories' => [
        ['slug' => 'kuafor', 'name' => 'Kuaför'],
        ['slug' => 'guzellik-salonu', 'name' => 'Güzellik Salonu'],
        ['slug' => 'berber', 'name' => 'Berber'],
    ],
    'posts' => [
        // ── KUAFÖR ──
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-nedir',
            'title' => 'Kuaför Nedir? Meslek Tanımı ve Görevleri',
            'seo_title' => 'Kuaför Nedir? | Seyfibaba Blog',
            'seo_description' => 'Kuaför mesleği nedir, hangi hizmetleri kapsar? Kısa ve net tanım.',
            'description' => '<p><strong>Kuaför</strong>, saç kesimi, boyama, bakım ve şekillendirme hizmeti veren, müşterinin yüz hatlarına uygun stil öneren profesyoneldir.</p><p>Günümüz kuaförü yalnızca makas kullanmaz; fön makinesi, düzleştirici, boya ve bakım ürünleriyle çalışır. Seyfibaba\'da kuaför salonları için profesyonel ekipman ve sarf malzeme bulabilirsiniz.</p><p><strong>İlginç bilgi:</strong> "Kuaför" kelimesi Fransızca <em>coiffeur</em> (saç düzenleyici) kelimesinden gelir.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuaforluk-tarihcesi',
            'title' => 'Kuaförlüğün Tarihçesi: Antik Çağdan Günümüze',
            'seo_title' => 'Kuaförlük Tarihçesi | Seyfibaba Blog',
            'seo_description' => 'Kuaförlük mesleğinin binlerce yıllık geçmişi — kısa tarih özeti.',
            'description' => '<p>M.Ö. 4000\'lerde <strong>Mısır</strong> ve Mezopotamya\'da saç bakımı statü sembolüydü. Antik Roma\'da berber-kuaför dükkânları sosyal buluşma noktasıydı.</p><p>1700\'lerde Paris\'te modern kuaförlük doğdu; 1900\'lerde elektrikli fön makinesi devrim yarattı. Türkiye\'de Cumhuriyet sonrası kadın kuaförleri hızla yayıldı.</p><p><strong>İlginç bilgi:</strong> Dünyanın bilinen en eski berber-kuaför aletleri Mısır mezarlarında bulunmuştur.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-nasil-olunur',
            'title' => 'Kuaför Nasıl Olunur? Türkiye\'de Yol Haritası',
            'seo_title' => 'Kuaför Nasıl Olunur? | Seyfibaba Blog',
            'seo_description' => 'Türkiye\'de kuaför olmak için eğitim, sertifika ve staj adımları.',
            'description' => '<p>Türkiye\'de kuaför olmak için genellikle şu adımlar izlenir:</p><ul><li>MEB onaylı <strong>kuaförlük kursu</strong> veya meslek lisesi</li><li>Usta öğreticilik / kalfalık belgesi (MYK)</li><li>Salonda staj ve portfolyo oluşturma</li><li>İsteğe bağlı: renk, keratin, extension uzmanlık eğitimleri</li></ul><p>Deneyim, sertifikadan daha hızlı güven kazandırır. Ekipman yatırımını Seyfibaba üzerinden karşılaştırarak başlayabilirsiniz.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-kataloglari',
            'title' => 'Kuaför Katalogları Nedir, Nasıl Kullanılır?',
            'seo_title' => 'Kuaför Katalogları Rehberi | Seyfibaba Blog',
            'seo_description' => 'Renk kartelası ve kesim katalogları kuaförde nasıl kullanılır?',
            'description' => '<p><strong>Kuaför katalogları</strong> müşteriye renk tonu, kesim modeli ve bakım seçeneklerini görsel olarak sunar.</p><ul><li><strong>Renk kartelası:</strong> Boya markasının ton skalası (ör. 6.0 koyu sarı)</li><li><strong>Kesim kitapları:</strong> Bob, katmanlı, pixie gibi modeller</li><li><strong>Fiyat listesi:</strong> Hizmet + süre + ürün maliyeti</li></ul><p>Doğru katalog seçimi, yanlış renk sürprizlerini azaltır ve satış ortalamasını yükseltir.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'iyi-kuafor-salonu-nasil-secilir',
            'title' => 'İyi Bir Kuaför Salonu Nasıl Anlaşılır?',
            'seo_title' => 'İyi Kuaför Salonu Seçimi | Seyfibaba Blog',
            'seo_description' => 'Kuaför seçerken hijyen, ekipman ve yorum kriterleri.',
            'description' => '<p>İyi kuaför salonu seçerken bakılacak 5 kriter:</p><ul><li><strong>Hijyen:</strong> Steril alet, temiz havlu, düzenli tezgah</li><li><strong>Portfolyo:</strong> Gerçek müşteri fotoğrafları</li><li><strong>Şeffaf fiyat:</strong> Sürpriz ek ücret yok</li><li><strong>Profesyonel ekipman:</strong> Kaliteli koltuk ve makineler</li><li><strong>Google/yorum puanı:</strong> 4.5+ ve güncel yorumlar</li></ul><p>Salon sahibiyseniz bu kriterleri karşılayan ekipmanı tek platformdan tedarik edebilirsiniz.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-koltugu-nasil-secilir',
            'title' => 'Kuaför Koltuğu Nasıl Seçilir? 7 Kritik Nokta',
            'seo_title' => 'Kuaför Koltuğu Seçim Rehberi | Seyfibaba Blog',
            'seo_description' => 'Hidrolik kuaför koltuğu alırken dikkat edilecekler.',
            'description' => '<p>Kuaför koltuğu salonunuzun en çok kullanılan yatırımıdır:</p><ul><li>Hidrolik pompa kalitesi ve garanti süresi</li><li>Döner mekanizma sessizliği</li><li>Suni deri / kumaş dayanıklılığı</li><li>Yıkama ünitesi uyumu (boyun açıklığı)</li><li>Minimum 120 kg taşıma kapasitesi</li><li>Kol dayama ve ayak desteği ergonomisi</li><li>Servis ağı ve yedek parça bulunabilirliği</li></ul><p><strong>İpucu:</strong> 4+ koltukta aynı model tercih edin; bakım maliyeti düşer.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-salonu-nasil-acilir',
            'title' => 'Kuaför Salonu Nasıl Açılır? Adım Adım',
            'seo_title' => 'Kuaför Salonu Açma Rehberi | Seyfibaba Blog',
            'seo_description' => 'Kuaför salonu açmak için planlama, ruhsat ve ekipman adımları.',
            'description' => '<p>Kuaför salonu açmak için temel adımlar:</p><ol><li><strong>Konum analizi:</strong> Yaya trafiği, rakip yoğunluğu, kira</li><li><strong>İş planı:</strong> Hizmet menüsü, fiyat, hedef müşteri</li><li><strong>Ruhsat ve vergi:</strong> Belediye işyeri açma, vergi levhası</li><li><strong>Dekorasyon + ekipman:</strong> Koltuk, ayna, tezgah, elektrik</li><li><strong>Personel ve stok:</strong> Boya, şampuan, sarf malzeme</li><li><strong>Pazarlama:</strong> Google İşletme, Instagram, açılış kampanyası</li></ol><p>Ekipman alışverişini toplu yaparak açılış bütçesini %15–20 düşürebilirsiniz.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-acma-sartlari-belgeler',
            'title' => 'Kuaför Açmak İçin Gerekli Belgeler ve Şartlar',
            'seo_title' => 'Kuaför Açma Şartları | Seyfibaba Blog',
            'seo_description' => 'Türkiye\'de kuaför salonu açmak için resmi belgeler listesi.',
            'description' => '<p>Türkiye\'de kuaför salonu açmak için genellikle gerekli belgeler:</p><ul><li>Vergi levhası (şahıs veya limited)</li><li>Belediye <strong>işyeri açma ruhsatı</strong></li><li>Yangın güvenlik raporu (metrekareye göre)</li><li>SGK işe giriş (çalışan varsa)</li><li>Ustalık / mesleki yeterlilik belgesi (MYK)</li><li>Kira sözleşmesi ve tapu izni</li></ul><p>İl ve ilçeye göre ek belgeler istenebilir; belediye zabıta müdürlüğünden güncel listeyi alın.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-acmak-maliyeti',
            'title' => 'Kuaför Açmak Maliyetli mi? 2026 Bütçe Özeti',
            'seo_title' => 'Kuaför Açma Maliyeti | Seyfibaba Blog',
            'seo_description' => 'Küçük ve orta ölçekli kuaför salonu açma maliyeti tahmini.',
            'description' => '<p>Kuaför açma maliyeti konuma göre değişir. 2026 için kabaca aralıklar:</p><ul><li><strong> Küçük salon (40–60 m²):</strong> 400.000 – 800.000 TL</li><li><strong>Orta salon (80–120 m²):</strong> 800.000 – 1.500.000 TL</li><li><strong>Ekipman payı:</strong> Toplam bütçenin %35–45\'i</li><li><strong>Dekorasyon:</strong> %25–30</li><li><strong>İlk stok (boya, sarf):</strong> %10–15</li></ul><p>Koltuk, tezgah ve makineleri tek seferde ve kampanyalı almak nakit akışını rahatlatır.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-ekipman-listesi',
            'title' => 'Kuaför Açmak İçin Zorunlu Ekipman Listesi',
            'seo_title' => 'Kuaför Ekipman Listesi | Seyfibaba Blog',
            'seo_description' => 'Yeni kuaför salonu için minimum ekipman checklist.',
            'description' => '<p>Yeni kuaför salonu için temel ekipman listesi (4 istasyon örneği):</p><ul><li>4 hidrolik kuaför koltuğu</li><li>2 yıkama ünitesi + berber lavabo</li><li>4 çalışma tezgahı + ayna</li><li>Fön makinesi, düzleştirici, maşa (istasyon başı)</li><li>Profesyonel makas seti (offset + thinning)</li><li>UV sterilizer veya autoklav</li><li>Boyama malzemeleri: tarak, fırça, tası, önlük</li><li>Şampuan, saç kremi, sabitleyici stok</li></ul><p><strong>Toplam parça:</strong> 40–60 kalem ekipman + sarf; tek tek değil set halinde alın.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-hijyen-onemi',
            'title' => 'Kuaförde Hijyen Neden Satışın Yarısıdır?',
            'seo_title' => 'Kuaför Hijyen İpuçları | Seyfibaba Blog',
            'seo_description' => 'Salon hijyeni müşteri güvenini ve tekrar ziyareti nasıl artırır?',
            'description' => '<p>Müşterilerin %78\'i (sektör anketleri) hijyeni fiyatın önünde tutar. Temel kurallar:</p><ul><li>Her müşteri sonrası tezgah silme</li><li>Tarak ve makas sterilizasyonu</li><li>Tek kullanımlık boya fırçası tercihi</li><li>Havlu ve önlük günlük değişim</li></ul><p>Görünür sterilizasyon cihazı güven algısını anında yükseltir — Seyfibaba\'da UV sterilizer modellerini inceleyin.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-ilginc-bilgiler',
            'title' => 'Kuaförlük Hakkında 5 İlginç Bilgi',
            'seo_title' => 'Kuaförlük İlginç Bilgiler | Seyfibaba Blog',
            'seo_description' => 'Kuaförlük mesleği hakkında az bilinen gerçekler.',
            'description' => '<ul><li>💇 Dünyanın en pahalı saç kesimi 2018\'de 1.500 sterlinle Londra\'da yapıldı.</li><li>✂️ Japon "samurai berber" geleneği ustura ile hâlâ yaşatılıyor.</li><li>🎨 İlk saç boyası antik Yunan\'da bitkisel kökenliydi.</li><li>📈 Türkiye\'de 2024 itibarıyla 150.000+ kayıtlı kuaför/berber işletmesi var.</li><li>🔥 Fön makinesi icat edilmeden önce doğal kurutma 45+ dakika sürüyordu.</li></ul><p>Bu bilgiler sosyal medya içeriği olarak da kullanılabilir — etkileşim getirir.</p>',
        ],

        // ── GÜZELLİK SALONU ──
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-nedir',
            'title' => 'Güzellik Salonu Nedir? Hizmet Kapsamı',
            'seo_title' => 'Güzellik Salonu Nedir? | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu tanımı ve sunduğu hizmetler — kısa rehber.',
            'description' => '<p><strong>Güzellik salonu</strong>; cilt bakımı, manikür-pedikür, epilasyon, makyaj, kaş-kirpik ve bazen masaj hizmetlerini bir arada sunan işletmedir.</p><p>Kuaförden farkı saç odaklı değil, <strong>cilt ve tırnak</strong> odaklı olmasıdır. Birçok salon hibrit modelle her iki hizmeti de verir.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-tarihcesi',
            'title' => 'Güzellik Salonlarının Tarihçesi',
            'seo_title' => 'Güzellik Salonu Tarihçesi | Seyfibaba Blog',
            'seo_description' => 'Güzellik endüstrisinin kısa tarihsel gelişimi.',
            'description' => '<p>Antik Mısır\'da kohl ile göz makyajı, Roma\'da banyo kültürü güzellik ritüellerinin temelini attı.</p><p>1900\'lerde Paris\'te ilk modern güzellik salonları açıldı. 1950\'lerde elektrikli cilt bakım cihazları yaygınlaştı. Günümüde Türkiye güzellik sektörü yıllık milyarlarca TL hacme ulaştı.</p><p><strong>İlginç bilgi:</strong> Kleopatra\'nın süt banyosu efsanesi aslında laktik asit içeren doğal peeling mantığına dayanır.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-uzmani-nasil-olunur',
            'title' => 'Güzellik Uzmanı Nasıl Olunur?',
            'seo_title' => 'Güzellik Uzmanı Olma Yolu | Seyfibaba Blog',
            'seo_description' => 'Güzellik uzmanı olmak için eğitim ve sertifika adımları.',
            'description' => '<p>Güzellik uzmanı olmak için:</p><ul><li>MEB onaylı <strong>güzellik ve cilt bakım</strong> kursu (600+ saat)</li><li>MYK güzellik uzmanı belgesi</li><li>Epilasyon, kalıcı makyaj için ek sertifikalar</li><li>Hijyen ve anatomi bilgisi</li></ul><p>Staj süresinde farklı cilt tiplerinde uygulama deneyimi kazanmak kariyerinizi hızlandırır.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-katalog',
            'title' => 'Güzellik Salonu Katalog ve Hizmet Menüsü',
            'seo_title' => 'Güzellik Salonu Katalog Rehberi | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu hizmet menüsü nasıl hazırlanır?',
            'description' => '<p>Etkili güzellik salonu katalogu şunları içermeli:</p><ul><li>Hizmet adı + süre + fiyat aralığı</li><li>Kullanılan marka / ürün (premium algısı)</li><li>Önce-sonra fotoğrafları</li><li>Paket indirimleri (cilt bakımı + manikür)</li></ul><p>QR kodlu dijital katalog müşterinin telefonunda kalır — tekrar randevu oranını artırır.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'iyi-guzellik-salonu-secimi',
            'title' => 'En İyi Güzellik Salonu Nasıl Seçilir?',
            'seo_title' => 'Güzellik Salonu Seçimi | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu seçerken dikkat edilecek 5 kriter.',
            'description' => '<p>Güzellik salonu seçerken:</p><ul><li><strong>Lisans / sertifika</strong> görünür mü?</li><li>Tek kullanımlık malzeme kullanılıyor mu?</li><li>Cihaz markaları profesyonel mi?</li><li>Randevu sistemi düzenli mi?</li><li>Allergi testi (boya, jel) yapılıyor mu?</li></ul><p>Salon sahibiyseniz bu standartları karşılayan ekipman yatırımı uzun vadede daha ucuzdur.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-koltugu-secimi',
            'title' => 'Güzellik Koltuğu ve Yatak Seçimi',
            'seo_title' => 'Güzellik Koltuğu Seçimi | Seyfibaba Blog',
            'seo_description' => 'Cilt bakım koltuğu ve manikür masası seçim ipuçları.',
            'description' => '<p>Güzellik salonunda iki temel oturma/yatma ünitesi vardır:</p><ul><li><strong>Cilt bakım koltuğu:</strong> Elektrikli, sırt ve ayak ayarı, su geçirmez döşeme</li><li><strong>Manikür/pedikür koltuğu:</strong> Entegre lavabo, masaj fonksiyonu (opsiyonel)</li></ul><p>Seçerken: motor sesi, deri kalitesi, servis garantisi ve yedek parça kontrol edin.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-nasil-acilir',
            'title' => 'Güzellik Salonu Nasıl Açılır?',
            'seo_title' => 'Güzellik Salonu Açma Rehberi | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu açmak için adım adım kısa rehber.',
            'description' => '<ol><li>Hedef kitle ve hizmet menüsü belirleyin (cilt mi, tırnak mı, hibrit mi?)</li><li>60–100 m² uygun lokasyon seçin</li><li>Ruhsat, yangın ve hijyen belgelerini tamamlayın</li><li>Elektrik altyapısını cihaz yüküne göre planlayın</li><li>Ekipman ve ilk stok alımını yapın</li><li>Sosyal medya + Google İşletme kaydı açın</li></ol><p>İlk 3 ayda paket kampanyaları ile müşteri tabanı oluşturun.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-acma-sartlari',
            'title' => 'Güzellik Salonu Açma Şartları ve Belgeler',
            'seo_title' => 'Güzellik Salonu Açma Şartları | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu açmak için resmi belgeler.',
            'description' => '<p>Güzellik salonu için kuaförle benzer resmi süreç geçerlidir:</p><ul><li>İşyeri açma ve çalışma ruhsatı</li><li>Vergi levhası</li><li>Mesleki yeterlilik belgesi (güzellik uzmanı)</li><li>Yangın tüpü ve acil çıkış planı</li><li>Atık bertaraf protokolü ( özellikle tek kullanımlık malzeme)</li></ul><p>Epilasyon ve medikal estetik hizmetler ek izin gerektirebilir.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-maliyeti',
            'title' => 'Güzellik Salonu Açma Maliyeti Ne Kadar?',
            'seo_title' => 'Güzellik Salonu Maliyeti | Seyfibaba Blog',
            'seo_description' => '2026 güzellik salonu açma bütçe tahmini.',
            'description' => '<p>Güzellik salonu açma maliyeti (2026 tahmini):</p><ul><li><strong>Butik salon (50 m²):</strong> 350.000 – 700.000 TL</li><li><strong>Tam donanımlı (100 m²+):</strong> 900.000 – 2.000.000 TL</li><li>Cihaz payı (cilt bakım, lazer): bütçenin %40\'ına kadar</li></ul><p>İkinci el profesyonel cihaz ve kampanyalı yeni ürün karışımı bütçeyi optimize eder.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-ekipman',
            'title' => 'Güzellik Salonu Ekipman Checklist',
            'seo_title' => 'Güzellik Salonu Ekipman Listesi | Seyfibaba Blog',
            'seo_description' => 'Yeni güzellik salonu için temel ekipman listesi.',
            'description' => '<ul><li>Elektrikli cilt bakım koltuğu (1–2 adet)</li><li>Manikür-pedikür seti + UV/LED kurutucu</li><li>Buhar makinesi ve cilt analiz cihazı</li><li>Epilasyon cihazı (ipl/lazer — lisanslı)</li><li>Sterilizasyon ünitesi</li><li>Malzeme dolabı ve tekerlekli servis arabası</li><li>Tek kullanımlık eldiven, havlu, ped seti</li></ul><p>Toplam 25–40 parça ekipman ile temel salon kurulabilir.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-ilginc',
            'title' => 'Güzellik Sektöründen 5 İlginç Bilgi',
            'seo_title' => 'Güzellik Sektörü İlginç Bilgiler | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonları hakkında ilginç gerçekler.',
            'description' => '<ul><li>💅 İlk nail art Japonya Edo döneminde soylular arasında modaydı.</li><li>🧴 C vitamini serumu pazarı son 5 yılda %200 büyüdü.</li><li>📱 Güzellik salonlarının %65\'i randevuyu WhatsApp ile alıyor.</li><li>🌿 "Clean beauty" trendi organik ürün talebini artırdı.</li><li>⏱️ Ortalama manikür seansı 45 dk, cilt bakımı 60–90 dk sürer.</li></ul>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'manikur-alani-planlama',
            'title' => 'Manikür-Pedikür Alanı Nasıl Planlanır?',
            'seo_title' => 'Manikür Alanı Planlama | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonunda manikür bölümü düzeni ipuçları.',
            'description' => '<p>Manikür alanı planlarken:</p><ul><li>Müşteri başına minimum 1,2 m genişlik</li><li>Lavabo + havalandırma zorunlu</li><li>UV lamba konumu göz hizasında olmamalı</li><li>Toz emici mat veya aspiratör kullanın</li><li>Aletler tekerlekli arabada kategorize edilsin</li></ul><p>Doğru planlama günlük 2–3 ekstra randevu kapasitesi sağlar.</p>',
        ],

        // ── BERBER ──
        [
            'category' => 'berber',
            'slug' => 'berber-nedir',
            'title' => 'Berber Nedir? Berber ile Kuaför Farkı',
            'seo_title' => 'Berber Nedir? | Seyfibaba Blog',
            'seo_description' => 'Berber mesleği tanımı ve kuaförden farkları.',
            'description' => '<p><strong>Berber</strong>, esas olarak erkek saç ve sakal bakımı yapan ustadır. Saç kesimi, sakal şekillendirme, ustura tıraş ve ense temizliği hizmetleri verir.</p><p><strong>Kuaförden farkı:</strong> Berber erkek model odaklıdır; kuaför kadın-erkek her iki segmentte renk ve styling derinliği sunar. Modern "barber shop" her iki geleneği birleştirir.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berberlik-tarihcesi',
            'title' => 'Berberlik Tarihçesi ve Türk Geleneği',
            'seo_title' => 'Berberlik Tarihçesi | Seyfibaba Blog',
            'seo_description' => 'Berberlik mesleğinin tarihi — Türk berber geleneği.',
            'description' => '<p>Osmanlı\'da berber dükkânı (<em>berberhane</em>) sadece tıraş yeri değil, gündem sohbetinin merkeziydi. Ustura tıraş geleneği günümüze kadar ulaştı.</p><p>Avrupa\'da 1800\'lerde berber-cerrah birlikteliği vardı; sonra ayrı meslekler oldu. Günümüzde fade kesim ve sakal bakımı berberliği yeniden popülerleştirdi.</p><p><strong>İlginç bilgi:</strong> Türkiye\'de "Cuma berberi" geleneği hâlâ en yoğun gündür.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-nasil-olunur',
            'title' => 'Berber Nasıl Olunur?',
            'seo_title' => 'Berber Nasıl Olunur? | Seyfibaba Blog',
            'seo_description' => 'Türkiye\'de berber olmak için eğitim yolu.',
            'description' => '<p>Berber olmak için:</p><ul><li>MEB berberlik / kuaförlük kursu veya meslek lisesi</li><li>MYK berber ustalık belgesi</li><li>Ustura ve makine tekniklerinde staj</li><li>Sakal şekillendirme ve fade kesim pratiği</li></ul><p>Sosyal medyada before/after paylaşımı portfolyonuzu hızla büyütür.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-katalog-fade',
            'title' => 'Berber Katalog ve Fade Kesim Rehberi',
            'seo_title' => 'Berber Fade Kesim Rehberi | Seyfibaba Blog',
            'seo_description' => 'Fade, taper ve skin fade kesim türleri — kısa rehber.',
            'description' => '<p>Berber kataloglarında en çok aranan modeller:</p><ul><li><strong>Low fade:</strong> Kulak hizasında geçiş</li><li><strong>Mid fade:</strong> Orta geçiş, en popüler</li><li><strong>Skin fade:</strong> Sıfıra yakın geçiş</li><li><strong>Taper:</strong> Yumuşak, doğal geçiş</li></ul><p>Müşteriye numara gösteren poster (0–4 guard) yanlış anlaşılmayı önler.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'iyi-berber-nasil-bulunur',
            'title' => 'İyi Berber Nasıl Bulunur?',
            'seo_title' => 'İyi Berber Seçimi | Seyfibaba Blog',
            'seo_description' => 'Kaliteli berber bulmak için pratik ipuçları.',
            'description' => '<p>İyi berber bulmak için:</p><ul><li>Google Maps\'te 4.5+ puan ve güncel fotoğraf</li><li>Fade ve sakal işçiliği portfolyosu</li><li>Alet hijyeni (UV kabı görünür mü?)</li><li>Randevu disiplini — bekleme süresi</li><li>Fiyat şeffaflığı (sakal dahil mi?)</li></ul>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-koltugu-secimi',
            'title' => 'Berber Koltuğu Nasıl Seçilir?',
            'seo_title' => 'Berber Koltuğu Seçimi | Seyfibaba Blog',
            'seo_description' => 'Berber koltuğu alırken dikkat edilecekler.',
            'description' => '<p>Berber koltuğu seçerken:</p><ul><li>Retro veya modern tarza uyum</li><li>Hidrolik gürültü seviyesi (dükkan atmosferi)</li><li>Ense yıkama uyumu</li><li>Deri rengi ve dikiş kalitesi</li><li>180° dönüş mekanizması</li></ul><p>2+ koltukta aynı model görsel bütünlük sağlar.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-dukkani-nasil-acilir',
            'title' => 'Berber Dükkanı Nasıl Açılır?',
            'seo_title' => 'Berber Dükkanı Açma Rehberi | Seyfibaba Blog',
            'seo_description' => 'Berber shop açmak için adım adım kısa rehber.',
            'description' => '<ol><li>25–50 m² yoğun yaya trafiği lokasyonu</li><li>Minimal dekorasyon + güçlü aydınlatma</li><li>2–4 berber koltuğu + 1 yıkama ünitesi</li><li>Ruhsat ve vergi işlemleri</li><li>Instagram/TikTok ile açılış tanıtımı</li></ol><p>Barber shop konseptinde bekleme alanı ve kahve ikramı müşteri sadakatini artırır.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-acma-sartlari',
            'title' => 'Berber Açma Şartları ve Ruhsat',
            'seo_title' => 'Berber Açma Şartları | Seyfibaba Blog',
            'seo_description' => 'Berber dükkanı açmak için resmi belgeler.',
            'description' => '<p>Berber dükkanı açmak kuaför ile aynı resmi çerçeveye tabidir: vergi levhası, işyeri ruhsatı, mesleki belge, yangın güvenliği. Belediye zabıtasından güncel listeyi alın.</p><p>Ev tipi işyeri (SOHO) bazı ilçelerde kısıtlı olabilir — önce zabıtaya danışın.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-acma-maliyeti',
            'title' => 'Berber Açmak Maliyetli mi?',
            'seo_title' => 'Berber Açma Maliyeti | Seyfibaba Blog',
            'seo_description' => '2026 berber dükkanı açma bütçe tahmini.',
            'description' => '<p>Berber dükkanı açma maliyeti (2026):</p><ul><li><strong> Küçük (2 koltuk):</strong> 250.000 – 500.000 TL</li><li><strong>Barber shop (3–4 koltuk):</strong> 500.000 – 900.000 TL</li><li>Ekipman payı: %40–50</li></ul><p>Kuaföre göre daha düşük metrekare ile açılabilir — ROI süresi genelde 12–18 ay.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-ekipman-listesi',
            'title' => 'Berber Dükkanı Ekipman Listesi',
            'seo_title' => 'Berber Ekipman Listesi | Seyfibaba Blog',
            'seo_description' => 'Berber dükkanı için zorunlu ekipman checklist.',
            'description' => '<ul><li>2–4 berber koltuğu (hidrolik)</li><li>1–2 yıkama ünitesi</li><li>Profesyonel makas + clipper seti</li><li>Ustura ve köpük kasesi</li><li>Ense temizleme fırçası ve pudra</li><li>UV sterilizer</li><li>Tezgah + ayna + LED aydınlatma</li><li>Bekleme koltuğu</li></ul><p><strong>Toplam:</strong> 20–30 parça ile çalışır dükkan kurulur.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-tezgah-ayna',
            'title' => 'Berber Tezgahı ve Ayna Yerleşimi',
            'seo_title' => 'Berber Tezgah Düzeni | Seyfibaba Blog',
            'seo_description' => 'Berber dükkanında tezgah ve ayna nasıl planlanır?',
            'description' => '<p>Tezgah ve ayna yerleşimi verimliliği doğrudan etkiler:</p><ul><li>Ayna genişliği minimum 80 cm</li><li>LED şerit aydınlatma gölge bırakmamalı</li><li>Tezgah derinliği 45–55 cm (alet düzeni için)</li><li>Clipper şarj istasyonu her istasyonda</li><li>Müşteri ile berber arası optimal mesafe: 60–70 cm</li></ul>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-ilginc-bilgiler',
            'title' => 'Berberlik Hakkında 5 İlginç Bilgi',
            'seo_title' => 'Berberlik İlginç Bilgiler | Seyfibaba Blog',
            'seo_description' => 'Berberlik mesleği hakkında ilginç gerçekler.',
            'description' => '<ul><li>💈 Berber direği kırmızı-beyaz spiral, tarihte kan letting döneminden kalma sembol.</li><li>✂️ Dünya sakal bakım pazarı yıllık %8 büyüyor.</li><li>🪒 Ustura tıraşı ciltte makineye göre daha az tahriş bırakabilir (doğru teknikle).</li><li>📊 Türkiye\'de erkek bakım harcaması son 10 yılda 3 kat arttı.</li><li>🎯 Fade kesim 2010\'dan sonra global berber trendini değiştirdi.</li></ul>',
        ],

        // ── KUAFÖR — ek çeşitli konular ──
        [
            'category' => 'kuafor',
            'slug' => '2026-sac-renk-trendleri',
            'title' => '2026 Saç Renk Trendleri: Kuaförler İçin Özet',
            'seo_title' => '2026 Saç Renk Trendleri | Seyfibaba Blog',
            'seo_description' => '2026\'da popüler saç renkleri — kuaförler için hızlı trend özeti.',
            'description' => '<p>2026\'da öne çıkan renkler:</p><ul><li><strong>Balayage 2.0:</strong> Doğal kök geçişi, düşük bakım</li><li><strong>Copper / bakır tonlar:</strong> Her ten rengine uyumlu</li><li><strong>Mocha melt:</strong> Kahve + karamel karışımı</li><li><strong>Face framing:</strong> Yüz çevresi aydınlatma</li></ul><p>Trend rengi uygularken kaliteli oksidan ve boya markası müşteri memnuniyetini doğrudan etkiler.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'balayage-ombre-farki',
            'title' => 'Balayage ve Ombre Arasındaki Fark Nedir?',
            'seo_title' => 'Balayage vs Ombre | Seyfibaba Blog',
            'seo_description' => 'Balayage ile ombre farkı — müşteriye nasıl anlatılır?',
            'description' => '<p><strong>Ombre:</strong> Kökten uca belirgin renk geçişi, genelde daha kontrast.</p><p><strong>Balayage:</strong> Elle sürülen yatay ışıltılar, daha doğal ve yumuşak geçiş.</p><p>Müşteri "doğal güneş yansımaları" istiyorsa balayage; "dramatik geçiş" istiyorsa ombre önerin. Her ikisi de farklı fırça ve foilyaj tekniği gerektirir.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-salonu-instagram',
            'title' => 'Kuaför Salonu Instagram Rehberi: 5 Hızlı İpucu',
            'seo_title' => 'Kuaför Instagram İpuçları | Seyfibaba Blog',
            'seo_description' => 'Kuaför salonu için Instagram içerik stratejisi.',
            'description' => '<ul><li>Before/after aynı ışıkta çekin</li><li>Reels\'te 15 sn\'lik dönüşüm videoları paylaşın</li><li>Haftada 1 "müşteri yorumu" story\'si</li><li>Hashtag: #sakaryakuaför gibi lokasyon odaklı kullanın</li><li>Profilde randevu linki (WhatsApp / web) sabitleyin</li></ul><p>Düzenli paylaşım yapan salonlar organik randevuda %30\'a kadar artış görür.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-randevu-sistemi',
            'title' => 'Kuaförde Randevu Sistemi Neden Şart?',
            'seo_title' => 'Kuaför Randevu Sistemi | Seyfibaba Blog',
            'seo_description' => 'Kuaför salonunda randevu yönetiminin faydaları.',
            'description' => '<p>Randevusuz çalışmak kapasite kaybıdır. Randevu sistemi:</p><ul><li>Boş slotları azaltır</li><li>Boya işlemleri için süre planlaması sağlar</li><li>No-show oranını düşürür (hatırlatma SMS)</li><li>Personel verimliliğini ölçer</li></ul><p>WhatsApp Business veya dijital takvim ile ücretsiz başlayabilirsiniz.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-en-cok-hatalar',
            'title' => 'Kuaför Salonlarında En Sık Yapılan 5 Hata',
            'seo_title' => 'Kuaför Salon Hataları | Seyfibaba Blog',
            'seo_description' => 'Yeni kuaför salonlarının yaptığı yaygın hatalar.',
            'description' => '<ul><li>❌ Ucuz ekipmanla başlayıp 6 ayda yenilemek (toplam maliyet artar)</li><li>❌ Fiyat listesi olmaması</li><li>❌ Sterilizasyonu görünür yapmamak</li><li>❌ Tek personelle aşırı randevu almak</li><li>❌ Stok takibi yapmamak — boya acil bitebilir</li></ul><p>Doğru ekipman yatırımı ilk günden başlar.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'gelin-saci-hazirligi',
            'title' => 'Gelin Saçı Hazırlığı: Kuaför İçin Kontrol Listesi',
            'seo_title' => 'Gelin Saçı Hazırlığı | Seyfibaba Blog',
            'seo_description' => 'Düğün saçı randevusu için kuaför kontrol listesi.',
            'description' => '<p>Gelin saçı randevusu öncesi:</p><ul><li>Prova randevusu 2–4 hafta önce</li><li>Vail / taç / çiçek provada test edilsin</li><li>Ekstra personel planlayın (düğün günü stresi azalır)</li><li>Sabitleyici sprey + pin stokunu 2 kat artırın</li></ul><p>Gelin paketi en yüksek marjlı hizmetlerden biridir — portfolyo oluşturun.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'keratin-bakim-nedir',
            'title' => 'Keratin Bakım Nedir? Kuaförler İçin Özet',
            'seo_title' => 'Keratin Bakım Rehberi | Seyfibaba Blog',
            'seo_description' => 'Keratin bakım hizmeti kuaförde nasıl sunulur?',
            'description' => '<p><strong>Keratin bakım</strong>, saç telini onarıp pürüzsüzleştiren, 2–4 ay etkili profesyonel işlemdir. Kuru, elektriklenen saçlar için idealdir.</p><p>Kuaför olarak: formaldahit içermeyen markalar tercih edin, havalandırma şart, müşteriye sonrası şampuan önerin (sülfatsız).</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-stok-yonetimi',
            'title' => 'Kuaför Malzemeleri Nasıl Stoklanır?',
            'seo_title' => 'Kuaför Stok Yönetimi | Seyfibaba Blog',
            'seo_description' => 'Salon boya ve sarf malzeme stok takibi ipuçları.',
            'description' => '<p>Stok kaosu randevu iptali demektir. Basit kurallar:</p><ul><li>Boya tüpü minimum stok: 2 haftalık tüketim</li><li>FIFO — eski ürün önce kullanılsın</li><li>Excel veya mobil stok uygulaması</li><li>Toplu alımda son kullanma tarihine dikkat</li></ul><p>Seyfibaba\'dan toplu sarf alımı birim maliyeti düşürür.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'kuafor-fiyatlandirma',
            'title' => 'Kuaför Fiyatlandırma: Nasıl Belirlenir?',
            'seo_title' => 'Kuaför Fiyatlandırma | Seyfibaba Blog',
            'seo_description' => 'Kuaför hizmet fiyatları nasıl hesaplanır?',
            'description' => '<p>Fiyat = malzeme maliyeti + süre × saatlik hedef + kira payı</p><ul><li>Boya işlemi: ürün maliyetini %15–25 ekle</li><li>Usta / kalfa kademesi farklı fiyat</li><li>Paket indirim yerine sadakat kartı düşünün</li></ul><p>Çok ucuz fiyat kalite algısını düşürür; piyasa araştırması yapın.</p>',
        ],
        [
            'category' => 'kuafor',
            'slug' => 'cocuk-kuafor-kosesi',
            'title' => 'Çocuk Kuaför Köşesi Nasıl Kurulur?',
            'seo_title' => 'Çocuk Kuaför Köşesi | Seyfibaba Blog',
            'seo_description' => 'Salonda çocuk saç kesimi alanı planlama ipuçları.',
            'description' => '<p>Çocuk müşteri aile paketi getirir. İhtiyaçlar:</p><ul><li>Renkli küçük koltuk veya booster oturak</li><li>Tablet / çizgi film dikkat dağıtıcı</li><li>Sessiz clipper (düşük desibel)</li><li>Sabır gerektiren ebeveyn saatlerinde ekstra personel</li></ul><p>Çocuk kesimi premium fiyatlandırılabilir — stres faktörü yüksektir.</p>',
        ],

        // ── GÜZELLİK SALONU — ek çeşitli konular ──
        [
            'category' => 'guzellik-salonu',
            'slug' => 'hydrafacial-nedir',
            'title' => 'Hydrafacial Nedir? Kısa Açıklama',
            'seo_title' => 'Hydrafacial Nedir? | Seyfibaba Blog',
            'seo_description' => 'Hydrafacial cilt bakımı hizmeti — güzellik salonları için özet.',
            'description' => '<p><strong>Hydrafacial</strong>, vakum + serum ile gözenek temizliği, peeling ve nemlendirme yapan tek seanslık cilt bakımıdır. 30–45 dk sürer, iyileşme süresi yoktur.</p><p>Salonunuzda cihaz yatırımı yüksek olabilir; seans başı fiyatlandırmayı buna göre yapın. Düğün öncesi paketlerde çok talep görür.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'kalici-oje-normal-oje-farki',
            'title' => 'Kalıcı Oje vs Normal Oje Farkı',
            'seo_title' => 'Kalıcı Oje Farkı | Seyfibaba Blog',
            'seo_description' => 'Kalıcı oje (gel) ile normal oje arasındaki farklar.',
            'description' => '<p><strong>Normal oje:</strong> 3–5 gün dayanır, kolay sökülür.</p><p><strong>Kalıcı oje (gel):</strong> UV/LED ile kürlenir, 2–3 hafta dayanır, profesyonel söküm gerekir.</p><p>Salon geliri açısından kalıcı oje daha yüksek marjlıdır; UV lambası ve base/top coat stoku şart.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'lazer-epilasyon-oncesi',
            'title' => 'Lazer Epilasyon Öncesi 5 Bilmeniz Gereken',
            'seo_title' => 'Lazer Epilasyon Öncesi | Seyfibaba Blog',
            'seo_description' => 'Lazer epilasyon öncesi müşteri hazırlığı — salon rehberi.',
            'description' => '<ul><li>Seans öncesi 24 saat tıraş (kök bırakmayın)</li><li>Güneşlenme sonrası 2 hafta bekleme</li><li>Hamilelik / ilaç kontrolü</li><li>İlk seans en düşük enerji ile test</li><li>6–8 seans paketi satın — sadakat artar</li></ul>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'guzellik-salonu-instagram',
            'title' => 'Güzellik Salonu Sosyal Medya: 4 İçerik Fikri',
            'seo_title' => 'Güzellik Salonu Instagram | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu için sosyal medya içerik fikirleri.',
            'description' => '<ul><li>⏱️ Manikür süreci timelapse (15 sn Reels)</li><li>✨ Cilt bakımı öncesi-sonrası (aynı ışık)</li><li>💡 "Cilt tipiniz hangisi?" interaktif anket</li><li>🎁 Ayın paketi duyurusu</li></ul><p>Haftada 3 paylaşım minimum; tutarlılık algoritma için kritik.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'cilt-tipine-gore-bakim',
            'title' => 'Cilt Tipine Göre Bakım Önerisi Tablosu',
            'seo_title' => 'Cilt Tipi Bakım Rehberi | Seyfibaba Blog',
            'seo_description' => 'Kuru, yağlı, karma cilt için salon bakım özeti.',
            'description' => '<ul><li><strong>Kuru:</strong> Hyaluronik nem maskesi, yağ bazlı serum</li><li><strong>Yağlı:</strong> Kil maskesi, hafif jel nemlendirici</li><li><strong>Karma:</strong> T-bölge yağ kontrol + yanak nem</li><li><strong>Hassas:</strong> Parfümsüz, alkol içermeyen ürünler</li></ul><p>Her müşteriye cilt analizi formu doldurun — tekrar ziyaret gerekçesi oluşur.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'kirpik-lifting-nedir',
            'title' => 'Kirpik Lifting Nedir? Salon Hizmeti Olarak',
            'seo_title' => 'Kirpik Lifting Rehberi | Seyfibaba Blog',
            'seo_description' => 'Kirpik lifting hizmeti — süre, fiyat ve dikkat noktaları.',
            'description' => '<p><strong>Kirpik lifting</strong>, doğal kirpikleri keratin solüsyonla kıvırıp boyayan 45–60 dk\'lık işlemdir. Maskara ihtiyacını 6–8 hafta azaltır.</p><p>Gerekli malzeme: silikon pad seti, lifting kit, tint boya. Düşük yatırımla yüksek talep gören hizmet.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'musteri-sadakati-programi',
            'title' => 'Güzellik Salonunda Müşteri Sadakati Nasıl Artırılır?',
            'seo_title' => 'Salon Müşteri Sadakati | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu sadakat programı fikirleri.',
            'description' => '<ul><li>6. seans %10 indirim kartı</li><li>Doğum günü ücretsiz kaş dizayn</li><li>Arkadaş getir — ikinize de indirim</li><li>WhatsApp hatırlatma: "3 hafta oldu, randevu?"</li></ul><p>Sadık müşteri edinme maliyeti yeni müşteriden 5 kat ucuzdur.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'salon-atmosferi-koku',
            'title' => 'Salon Atmosferi ve Koku Markalaşması',
            'seo_title' => 'Salon Atmosferi | Seyfibaba Blog',
            'seo_description' => 'Güzellik salonu ambiyans ve koku seçimi.',
            'description' => '<p>Müşteri salonunuzu kokusundan hatırlar. İpuçları:</p><ul><li>Hafif nane-çay ağacı ferahlığı tercih edin (ağır parfüm baş ağrısı yapar)</li><li>Mum / difüzör girişte konumlandırın</li><li>Lo-fi veya soft jazz — 60–70 dB</li><li>LED sıcak ton aydınlatma (4000K)</li></ul>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'agda-wax-farki',
            'title' => 'Ağda mı Wax mı? Fark ve Salon Seçimi',
            'seo_title' => 'Ağda vs Wax | Seyfibaba Blog',
            'seo_description' => 'Ağda ve wax epilasyon farkı — hangisi ne zaman?',
            'description' => '<p><strong>Ağda (sıcak):</strong> Kısa tüyleri kökünden alır, ince tüylerde etkili, cilt sıcaklığında uygulanır.</p><p><strong>Wax (soğuk/ılık):</strong> Daha hızlı uygulama, geniş alanlar (bacak) için pratik.</p><p>Hassas ciltte hipollerjenik wax markası; bacak ve kol için ağda tercih edilebilir.</p>',
        ],
        [
            'category' => 'guzellik-salonu',
            'slug' => 'yaz-cilt-bakimi',
            'title' => 'Yaz Aylarında Cilt Bakımı: Salon Önerileri',
            'seo_title' => 'Yaz Cilt Bakımı | Seyfibaba Blog',
            'seo_description' => 'Yaz sezonu cilt bakım hizmetleri — güzellik salonu rehberi.',
            'description' => '<p>Yaz paketi fikirleri:</p><ul><li>SPF içerikli nemlendirme bakımı</li><li>Gözenek sıkılaştırma maskesi</li><li>After-sun yatıştırıcı serum</li><li>Hafif BB glow makyaj</li></ul><p>Lazer seanslarını yaz ortasında duraklatın — güneş lekesi riski artar.</p>',
        ],

        // ── BERBER — ek çeşitli konular ──
        [
            'category' => 'berber',
            'slug' => 'sakal-bakim-yagi',
            'title' => 'Sakal Bakım Yağı Nedir, Nasıl Önerilir?',
            'seo_title' => 'Sakal Bakım Yağı | Seyfibaba Blog',
            'seo_description' => 'Berberde sakal yağı satışı ve uygulama ipuçları.',
            'description' => '<p>Sakal yağı kuruluğu giderir, kaşıntıyı azaltır. Berber olarak:</p><ul><li>Kesim sonrası 2–3 damla demo uygulayın</li><li>Argan + jojoba karışımı çoğu cilde uyar</li><li>Küçük şişe retail satış — ek gelir kaynağı</li></ul><p>"Sakal paketi" (kesim + yağ + sıcak havlu) fiyatı %20 artırılabilir.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'sicak-havlu-tiras',
            'title' => 'Sıcak Havlu Tıraş Ritüeli Nedir?',
            'seo_title' => 'Sıcak Havlu Tıraş | Seyfibaba Blog',
            'seo_description' => 'Hot towel shave berber ritüeli — adım adım.',
            'description' => '<p>Klasik berber deneyiminin kalbi:</p><ol><li>Sıcak havlu ile 2–3 dk bekletme (kıl yumuşatma)</li><li>Köpük uygulama fırçası ile</li><li>Ustura veya shavette tıraş</li><li>Soğuk havlu kapatma (gözenek kapatma)</li><li>Aftershave balsam</li></ol><p>Premium hizmet olarak 2–3 kat fiyatlandırılabilir.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'clipper-trimmer-farki',
            'title' => 'Clipper ve Trimmer Farkı Nedir?',
            'seo_title' => 'Clipper vs Trimmer | Seyfibaba Blog',
            'seo_description' => 'Berber clipper ve trimmer arasındaki fark — hangisi ne işe yarar?',
            'description' => '<p><strong>Clipper:</strong> Geniş başlık, fade ve bulk kesim, güçlü motor.</p><p><strong>Trimmer:</strong> İnce başlık, sakal hattı, ense detayı, zero gap ayarı.</p><p>Profesyonel berber her ikisini de kullanır; kablosuz model hareket özgürlüğü sağlar.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-upsell-paket',
            'title' => 'Berberde Paket Satış: Geliri Artırmanın Yolu',
            'seo_title' => 'Berber Paket Satış | Seyfibaba Blog',
            'seo_description' => 'Berber dükkanında upsell ve paket fiyatlandırma fikirleri.',
            'description' => '<p>Tek kesim yerine paket sunun:</p><ul><li><strong>Classic:</strong> Saç + ense</li><li><strong>Premium:</strong> Saç + sakal + sıcak havlu</li><li><strong>VIP:</strong> Premium + yüz maskesi + sakal yağı</li></ul><p>Paket fiyatı tekil toplamdan %10 ucuz görünsün — dönüşüm artar.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'cocuk-tirasi-ipuclari',
            'title' => 'Çocuk Tıraşı: Berber İçin 4 Pratik İpucu',
            'seo_title' => 'Çocuk Tıraşı İpuçları | Seyfibaba Blog',
            'seo_description' => 'Berberde çocuk saç kesimi nasıl kolaylaştırılır?',
            'description' => '<ul><li>Sessiz clipper kullanın</li><li>İlk 30 saniyede güven verin — sohbet edin</li><li>Ödül sticker / şeker (ebeveyn izniyle)</li><li>Hızlı ol — ideal süre 10–15 dk</li></ul><p>Mutlu çocuk = tekrar gelen aile.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'sakal-sekillendirme-2026',
            'title' => '2026 Sakal Modelleri: Berberler İçin Özet',
            'seo_title' => '2026 Sakal Modelleri | Seyfibaba Blog',
            'seo_description' => 'Popüler sakal şekillendirme modelleri 2026.',
            'description' => '<ul><li><strong>Short boxed beard:</strong> Yanakta temiz hat</li><li><strong>Stubble 3 gün:</strong> Düşük bakım trendi</li><li><strong>Full beard + fade:</strong> Yanak geçişli tam sakal</li><li><strong>Goatee modern:</strong> Genç segmentte popüler</li></ul><p>Duvar posteri ile müşteriye model seçtirin — yanlış anlaşılma azalır.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-dukkani-marka',
            'title' => 'Berber Dükkanı Markalaşması: İsimden Logoya',
            'seo_title' => 'Berber Markalaşma | Seyfibaba Blog',
            'seo_description' => 'Berber shop marka kimliği oluşturma ipuçları.',
            'description' => '<p>Barber shop markası:</p><ul><li>Kısa, akılda kalıcı isim (2–3 hece ideal)</li><li>Siyah-beyalt-altın renk paleti klasik tercih</li><li>Logo: makas veya ustura silüeti</li><li>Önlük ve peşkirde logo baskısı</li><li>Google İşletme fotoğrafları profesyonel olsun</li></ul>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-musteri-bekleme',
            'title' => 'Berber Dükkanında Bekleme Alanı Nasıl Olmalı?',
            'seo_title' => 'Berber Bekleme Alanı | Seyfibaba Blog',
            'seo_description' => 'Berber shop bekleme alanı düzeni ve müşteri deneyimi.',
            'description' => '<p>Bekleme alanı satışa dönüşür:</p><ul><li>2–4 kişilik deri koltuk veya bank</li><li>Magazine + şarj istasyonu</li><li>Sakal yağı / wax retail standı</li><li>Duvar TV\'de spor veya berber videoları</li></ul><p>Beklerken satılan ürün stresi azaltır ve gelir ekler.</p>',
        ],
        [
            'category' => 'berber',
            'slug' => 'ense-temizleme-teknikleri',
            'title' => 'Ense Temizleme Teknikleri: Berber Rehberi',
            'seo_title' => 'Ense Temizleme Teknikleri | Seyfibaba Blog',
            'seo_description' => 'Profesyonel ense temizleme ve fade birleştirme ipuçları.',
            'description' => '<p>Temiz ense berber kalitesinin göstergesidir:</p><ul><li>0 guard ile outline çiz</li><li>T-blade ile detay</li><li>Ense fırçası + pudra ile döküntü temizliği</li><li>Ayna ile arka kontrol müşteriye gösterin</li></ul>',
        ],
        [
            'category' => 'berber',
            'slug' => 'berber-cuma-yogunlugu',
            'title' => 'Cuma Yoğunluğu: Berber Nasıl Yönetilir?',
            'seo_title' => 'Berber Cuma Yoğunluğu | Seyfibaba Blog',
            'seo_description' => 'Cuma günü berber dükkanı kapasite yönetimi.',
            'description' => '<p>Cuma en yoğun gün — planlama şart:</p><ul><li>Ekstra personel veya uzatılmış mesai</li><li>Online randevu zorunlu yapın</li><li>Hızlı kesim (30 dk slot) + detaylı kesim (45 dk) ayırın</li><li>Çay/kahve ikramı bekleme stresini azaltır</li></ul><p>Cuma gününe %10 prim personel motivasyonu sağlar.</p>',
        ],
    ],
];
