// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11_y_pNKkykjJQHs9SemiHM7JBcr-Msg',
    appId: '1:471616289470:web:02d851bc95ba61f9913cef',
    messagingSenderId: '471616289470',
    projectId: 'shopo-ecommerce',
    authDomain: 'shopo-ecommerce.firebaseapp.com',
    storageBucket: 'shopo-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3ShHSc-MEqu5T3prIP-ZzBu2juWCfdM',
    appId: '1:967339992980:android:0ca347d85b18e54a395181',
    messagingSenderId: '967339992980',
    projectId: 'seyfibabapp',
    storageBucket: 'seyfibabapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBetbIVhGVPFSeoPb7dWYXV42N2rnzkh-Y',
    appId: '1:967339992980:ios:7f9f25da2c7e6b64395181',
    messagingSenderId: '967339992980',
    projectId: 'seyfibabapp',
    storageBucket: 'seyfibabapp.firebasestorage.app',
    iosBundleId: 'com.seyfibaba.app',
  );
}
